'use client';

import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded';
import SaveRoundedIcon from '@mui/icons-material/SaveRounded';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, FormControl, InputLabel, MenuItem, Select, Stack, Switch, TextField, Typography } from '@mui/material';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { AuthGuard } from '@/components/AuthGuard';
import { operationsService } from './operations.service';

function Shell({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <AuthGuard><AppShell><Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>{title}</Typography><Typography color="text.secondary">{description}</Typography></Box>{children}</Stack></AppShell></AuthGuard>;
}

function Loading() { return <Stack alignItems="center" py={6}><CircularProgress /></Stack>; }
const dt = (value: string) => value ? new Date(value).toLocaleString('pt-BR') : '-';

export function MessagesPage() {
  const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [search,setSearch]=useState(''); const [direction,setDirection]=useState(''); const [status,setStatus]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await operationsService.messages({search,direction,status,limit:100});setRows(result.data??[]);}catch(e:any){setError(e?.response?.data?.error||'Não foi possível carregar as mensagens.');}finally{setLoading(false);}},[search,direction,status]);
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>rows,[rows]);
  return <Shell title="Mensagens" description="Consulte mensagens recebidas e enviadas sem atualizar a página em loop."><Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} spacing={2} mb={3}><TextField fullWidth size="small" label="Buscar destino, conteúdo ou ID" value={search} onChange={e=>setSearch(e.target.value)}/><FormControl size="small" sx={{minWidth:160}}><InputLabel>Direção</InputLabel><Select label="Direção" value={direction} onChange={e=>setDirection(e.target.value)}><MenuItem value="">Todas</MenuItem><MenuItem value="inbound">Recebidas</MenuItem><MenuItem value="outbound">Enviadas</MenuItem></Select></FormControl><TextField size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}/><Button variant="outlined" startIcon={<RefreshRoundedIcon/>} onClick={()=>void load()}>Filtrar</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading?<Loading/>:<Box sx={{overflowX:'auto'}}><Box sx={{minWidth:900}}>{filtered.map(row=><Stack key={row.id} direction="row" spacing={2} alignItems="center" sx={{py:1.5,borderBottom:'1px solid',borderColor:'divider'}}><Typography variant="body2" sx={{width:150}}>{dt(row.created_at)}</Typography><Typography variant="body2" sx={{width:150}} noWrap>{row.instance_name||row.session}</Typography><Typography variant="body2" sx={{width:180}} noWrap>{row.remote_jid}</Typography><Chip size="small" label={row.direction==='inbound'?'Recebida':'Enviada'} color={row.direction==='inbound'?'info':'primary'}/><Typography variant="body2" sx={{width:110}}>{row.message_type}</Typography><Chip size="small" label={row.status}/><Typography variant="body2" sx={{flex:1}} noWrap>{row.body||row.media_url||'-'}</Typography></Stack>)}{!filtered.length&&<Alert severity="info">Nenhuma mensagem encontrada.</Alert>}</Box></Box>}</CardContent></Card></Shell>;
}

export function MetricsPage() {
  const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await operationsService.metrics());}catch(e:any){setError(e?.response?.data?.error||'Não foi possível carregar as métricas.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  if(loading)return <Shell title="Métricas" description="Indicadores operacionais do gateway."><Loading/></Shell>;
  const cards=[['Instâncias',data?.instances?.total],['Conectadas',data?.instances?.connected],['Mensagens hoje',data?.messages?.today],['Falhas hoje',data?.messages?.failed],['Fila pendente',data?.queue?.queued],['Webhooks com falha',data?.webhooks?.failed],['Tempo médio webhook',`${data?.webhooks?.avg_ms??0} ms`]];
  return <Shell title="Métricas" description="Indicadores operacionais do gateway, carregados sob demanda."><Stack direction="row" justifyContent="flex-end"><Button variant="outlined" startIcon={<RefreshRoundedIcon/>} onClick={()=>void load()}>Atualizar</Button></Stack>{error&&<Alert severity="error">{error}</Alert>}<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',lg:'repeat(4,1fr)'},gap:2}}>{cards.map(([label,value])=><Card key={String(label)} variant="outlined"><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h4" fontWeight={800} mt={1}>{value??0}</Typography></CardContent></Card>)}</Box><Card variant="outlined"><CardContent><Typography variant="h6" fontWeight={800} mb={2}>Últimas 24 horas</Typography>{(data?.hourly??[]).map((row:any)=><Stack key={row.hour} direction="row" spacing={2} sx={{py:1,borderBottom:'1px solid',borderColor:'divider'}}><Typography sx={{width:180}}>{dt(row.hour)}</Typography><Typography>Total: {row.total}</Typography><Typography>Recebidas: {row.inbound}</Typography><Typography>Enviadas: {row.outbound}</Typography></Stack>)}</CardContent></Card></Shell>;
}

export function LogsPage() {
  const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [status,setStatus]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await operationsService.logs({search,status,limit:100});setRows(result.data??[]);}catch(e:any){setError(e?.response?.data?.error||'Não foi possível carregar os logs.');}finally{setLoading(false);}},[search,status]);
  useEffect(()=>{void load();},[]);
  return <Shell title="Logs" description="Eventos de conexão pesquisáveis por instância e status."><Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} spacing={2} mb={3}><TextField fullWidth size="small" label="Buscar instância ou motivo" value={search} onChange={e=>setSearch(e.target.value)}/><TextField size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}/><Button variant="outlined" startIcon={<RefreshRoundedIcon/>} onClick={()=>void load()}>Filtrar</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading?<Loading/>:<Box sx={{overflowX:'auto'}}><Box sx={{minWidth:850}}>{rows.map(row=><Stack key={row.id} direction="row" spacing={2} alignItems="center" sx={{py:1.5,borderBottom:'1px solid',borderColor:'divider'}}><Typography variant="body2" sx={{width:160}}>{dt(row.created_at)}</Typography><Typography variant="body2" sx={{width:170}} noWrap>{row.instance_name||row.session}</Typography><Chip size="small" label={row.status} color={row.status==='connected'?'success':row.status==='error'?'error':'default'}/><Typography variant="body2" sx={{flex:1}}>{row.reason||'-'}</Typography><Typography variant="caption">Código: {row.disconnect_code??'-'}</Typography></Stack>)}{!rows.length&&<Alert severity="info">Nenhum log encontrado.</Alert>}</Box></Box>}</CardContent></Card></Shell>;
}

export function SettingsPage() {
  const [values,setValues]=useState<any>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{void operationsService.settings().then(setValues).catch((e:any)=>setError(e?.response?.data?.error||'Não foi possível carregar as configurações.')).finally(()=>setLoading(false));},[]);
  async function save(){setSaving(true);setError('');try{setValues(await operationsService.saveSettings(values));setMessage('Configurações salvas com sucesso.');}catch(e:any){setError(e?.response?.data?.error||'Não foi possível salvar.');}finally{setSaving(false);}}
  if(loading)return <Shell title="Configurações" description="Parâmetros operacionais por empresa."><Loading/></Shell>;
  return <Shell title="Configurações" description="Parâmetros operacionais persistidos por empresa.">{error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success" onClose={()=>setMessage('')}>{message}</Alert>}<Card variant="outlined"><CardContent><Stack spacing={2.5}><TextField label="Retenção de dados (dias)" type="number" value={values.retention_days} onChange={e=>setValues({...values,retention_days:Number(e.target.value)})}/><TextField label="Máximo de tentativas da fila" type="number" value={values.queue_max_attempts} onChange={e=>setValues({...values,queue_max_attempts:Number(e.target.value)})}/><TextField label="Timeout de webhook (ms)" type="number" value={values.webhook_timeout_ms} onChange={e=>setValues({...values,webhook_timeout_ms:Number(e.target.value)})}/><FormControl><InputLabel>Nível de log</InputLabel><Select label="Nível de log" value={values.log_level} onChange={e=>setValues({...values,log_level:e.target.value})}><MenuItem value="debug">Debug</MenuItem><MenuItem value="info">Info</MenuItem><MenuItem value="warn">Warn</MenuItem><MenuItem value="error">Error</MenuItem></Select></FormControl>{[['auto_reconnect','Reconectar automaticamente'],['store_message_body','Armazenar conteúdo das mensagens'],['store_raw_payload','Armazenar payload bruto']].map(([key,label])=><Stack key={key} direction="row" justifyContent="space-between" alignItems="center"><Typography>{label}</Typography><Switch checked={Boolean(values[key])} onChange={e=>setValues({...values,[key]:e.target.checked})}/></Stack>)}<Button variant="contained" startIcon={<SaveRoundedIcon/>} disabled={saving} onClick={()=>void save()}>{saving?'Salvando...':'Salvar configurações'}</Button></Stack></CardContent></Card></Shell>;
}
